### ISSUE TITLE
ARM release

### ISSUE THREAD

**Issue by hlaueriksson** [NaroZeol/PowerHexInspector#1]
Hi @NaroZeol

It would be nice to get an `ARM` release of the plugin.

**Comment by hlaueriksson** [comment]
The [community plugin checklist](https://github.com/hlaueriksson/awesome-powertoys-run-plugins/blob/main/checklist.md) has some pointers on the naming convention for the zip files.

**Comment by NaroZeol** [comment]
> Hi @NaroZeol
> 
> It would be nice to get an `ARM` release of the plugin.

Yes, it should be.
But unfortunately I don't have an ARM machine.
Can you tell me the right way to build an ARM release?



> The [community plugin checklist](https://github.com/hlaueriksson/awesome-powertoys-run-plugins/blob/main/checklist.md) has some pointers on the naming convention for the zip files.

OK, I will checkout later to make them nice to the checklist.

**Comment by hlaueriksson** [comment]
I'll build the `ARM64` DLLs from source.

The devdocs contains instructions to get started; https://github.com/microsoft/PowerToys/tree/main/doc/devdocs#compiling-powertoys

**Comment by hlaueriksson** [comment]
If you get stuck, I can write in more details.

**Comment by NaroZeol** [comment]
OK, I will try it later.

**Comment by NaroZeol** [comment]
Hey @hlaueriksson
I have already finished ARM64 support in [dev branch](https://github.com/NaroZeol/PowerHexInspector/tree/dev)
But I have no idea whether it can work on ARM64 because I don't have an ARM machine

Do you know any way to test it on my computer?

**Comment by hlaueriksson** [comment]
No, as far as I know, you need an ARM processor to test it for real.
I test my `x64` releases on my computer and hope that the `ARM64` versions work 😁

**Comment by NaroZeol** [comment]
I think a software based emulator like  [qemu](https://github.com/qemu/qemu) should be helpful.
But it's a bit awkward that we need to test a simple plugin by downloading and installing another large software. 🤐

So maybe there should be an official guide to build ARM64 release. 🤥

**Comment by hlaueriksson** [comment]
> So maybe there should be an official guide to build ARM64 release. 🤥

Yes, if you create an issue in the PowerToys repo and ask for that, I will give it a 👍

**Comment by NaroZeol** [comment]
> Yes, if you create an issue in the PowerToys repo and ask for that, I will give it a 👍

Haha, it seems not suitable for a beginner like me to ask for that.

**Comment by hlaueriksson** [comment]
Don't be so humble 😸
I think alot of people would be interested in that guide.

**Comment by hlaueriksson** [comment]
I created a NuGet package that simplifies referencing the `ARM64` dependencies:

- https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Dependencies

**Comment by NaroZeol** [comment]
Amazing one!
No need to take tens of minutes to build dependencies any more!
