### ISSUE TITLE
[Feature Request] Make `base` optional (default 10) to simplify input

### ISSUE THREAD

**Issue by pilgrimlyieu** [NaroZeol/PowerHexInspector#2]
It means that `insp 11` is as same as `insp d 11`. Use 10 as default base since it makes intuitive sense in most cases.

**Comment by NaroZeol** [comment]
> It means that `insp 11` is as same as `insp d 11`. Use 10 as default base since it makes intuitive sense in most cases.

Nice idea !
I will work on it  soon.

**Comment by pilgrimlyieu** [comment]
Some additional suggestions:
1. Add `o/O` standing for octal
2. `insp 07` --> `insp o 7`
3. `insp 0b1101` --> `insp b 1101`
4. `insp 0xffff` --> `insp h ffff`

**Comment by NaroZeol** [comment]
> Some additional suggestions:
> 
> 1. Add `o/O` standing for octal
> 2. `insp 07` --> `insp o 7`
> 3. `insp 0b1101` --> `insp b 1101`
> 4. `insp 0xffff` --> `insp h ffff`

1.Of course, octal should be supported.

2.Well, I don't think `0` and `o` can have same meaning.

3 and 4. Actually `0x` is legal for this version, but its implementation is to simply filter `0x` characters. I will rebuild this part to make it more useful.

**Comment by pilgrimlyieu** [comment]
> 2.Well, I don't think `0` and `o` can have same meaning.

I mean C style, where number starts with `0` is interpreted as octal number.

**Comment by NaroZeol** [comment]
> I mean C style, where number starts with `0` is interpreted as octal number.

I got it. This makes sense.

**Comment by NaroZeol** [comment]
Hey @[pilgrimlyieu](https://github.com/pilgrimlyieu)

New version has been released ! 

https://github.com/NaroZeol/PowerHexInspector/releases/tag/v0.3.0

**Comment by pilgrimlyieu** [comment]
> New version has been released !

It works well! Thanks for your efforts.

By the way, octal sign `o/O` is not included in valid base values in README.

**Comment by NaroZeol** [comment]
> By the way, octal sign o/O is not included in valid base values in README.

Fixed.

The previous v0.3.0 release had something wrong with endian option.
Try the new one to avoid that.

May be I should have some auto testings to avoid such things 😥😥😥
